on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fetch latest release tag from luci-app-unblockneteasemusic
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/UnblockNeteaseMusic/luci-app-unblockneteasemusic/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          
      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Download latest unblockneteasemusic files
        run: |
          # 下载最新 release 的 ipk 包
          mkdir -p unblockneteasemusic_all
          cd unblockneteasemusic_all
          
          # 获取所有 ipk 文件的下载链接
          curl -s https://api.github.com/repos/UnblockNeteaseMusic/luci-app-unblockneteasemusic/releases/latest | \
            jq -r '.assets[] | select(.name | endswith(".ipk")) | .browser_download_url' | \
            xargs -n 1 curl -LO
          
          cd ..

      - name: Organize files
        run: |
          pushd "unblockneteasemusic_all" >/dev/null || exit 1
          
          # 去除文件名中的 ~ 字符
          for file in *~*.ipk; do
            [ -e "$file" ] || continue
            new_file="$(echo "$file" | tr -d '~')"
            if [ -e "$new_file" ]; then
              echo "目标文件已存在，跳过: $new_file"
              continue
            fi
            mv "$file" "$new_file"
            echo "已重命名: $file -> $new_file"
          done
          
          popd >/dev/null
          
      - name: Create install.sh script
        run: |
          cat <<'EOF' > unblockneteasemusic_all/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed."
              exit 1
          fi
          opkg install *.ipk
          EOF
          chmod +x unblockneteasemusic_all/install.sh
          
      - name: Move directory to makeself
        run: |
          mv unblockneteasemusic_all makeself/
          
      - name: Create self-extracting package
        run: |
          cd makeself
          ./makeself.sh unblockneteasemusic_all/ luci-app-unblockneteasemusic_${{ env.LATEST_TAG }}_all.run "UnblockNeteaseMusic installer by github action" ./install.sh
          
      - name: Check file size
        run: |
          ls -lh makeself/luci-app-unblockneteasemusic_*.run
          
      - name: Upload run file as release asset
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: unblockneteasemusic
          name: "luci-app-unblockneteasemusic"
          files: makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "[!Github [<sup>1</sup>](https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://wkdaily.cpolar.cn/archives/1)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
